# Generated by Django 4.1.7 on 2023-03-03 05:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
