# Generated by Django 4.1.7 on 2023-03-03 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_delete_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayWeateher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('precipitation', models.FloatField()),
                ('temperature', models.FloatField()),
                ('was_raining', models.BooleanField()),
            ],
        ),
        migrations.DeleteModel(
            name='Game',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
