# Generated by Django 4.1.7 on 2023-03-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_alien_weapon_remove_book_authors_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=256)),
                ('is_done', models.BooleanField()),
                ('priority', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Alien',
        ),
        migrations.DeleteModel(
            name='Weapon',
        ),
    ]
