# Generated by Django 4.1.7 on 2023-03-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_dayweateher_delete_game_delete_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartments', models.IntegerField()),
                ('house_number', models.IntegerField()),
                ('street', models.CharField(max_length=64)),
            ],
        ),
    ]
