# Generated by Django 4.1.7 on 2023-03-03 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('author', models.CharField(max_length=30)),
                ('pages_count', models.IntegerField()),
                ('genre', models.CharField(max_length=30)),
                ('book_cost', models.DecimalField(decimal_places=2, max_digits=6)),
                ('status', models.CharField(max_length=30)),
            ],
        ),
    ]
